/** NIP-29 / Obscur community relay event kinds used by sealed community ingest. */
export const SEALED_COMMUNITY_KIND_SEALED = 10105;
export const SEALED_COMMUNITY_KIND_DELETE = 5;
export const SEALED_COMMUNITY_KIND_METADATA = 39000;
export const SEALED_COMMUNITY_KIND_MEMBERS = 39002;
export const SEALED_COMMUNITY_KIND_REQUEST_JOIN = 9021;
export const SEALED_COMMUNITY_KIND_LEAVE = 9022;

/** Path B B1-2: chat-only subscription for managed_workspace (no roster/join/leave kinds). */
export const SEALED_COMMUNITY_CHAT_SUBSCRIBE_KINDS = [
  SEALED_COMMUNITY_KIND_SEALED,
  SEALED_COMMUNITY_KIND_DELETE,
] as const;

export const SEALED_COMMUNITY_TIMELINE_SUBSCRIBE_KINDS = [
  SEALED_COMMUNITY_KIND_SEALED,
  SEALED_COMMUNITY_KIND_DELETE,
  SEALED_COMMUNITY_KIND_METADATA,
  SEALED_COMMUNITY_KIND_MEMBERS,
  SEALED_COMMUNITY_KIND_REQUEST_JOIN,
  SEALED_COMMUNITY_KIND_LEAVE,
] as const;
