/**
 * B5 legacy subtraction manifest — quarantine targets and amputation proof.
 *
 * @see apps/pwa/app/legacy/QUARANTINE.md
 * @see docs/program/obscur-backend-engine-roadmap.md §B5
 */

/** Active quarantine — do not extend; delete when importer count reaches zero. */
export const ENGINE_LAB_QUARANTINE_TARGETS = [] as const;

/** Removed — gate fails if these paths reappear. */
export const ENGINE_LAB_SUBTRACTED_FILES = [
  "app/features/messaging/services/dm-authority-drift-detector.ts",
  "app/features/messaging/services/dm-delete-event-log-reconciliation.ts",
  "app/features/messaging/services/dm-delete-event-log-reconciliation.test.ts",
  "app/features/messaging/services/realtime-voice-ui-visibility.ts",
  "app/features/messaging/services/realtime-voice-ui-visibility.test.ts",
  "app/features/messaging/hooks/use-conversation-messages-fixed.ts",
  "app/features/messaging/services/dm-conversation-materialization-port.ts",
  "app/features/messaging/components/message-list-scroll-debug.ts",
  "app/features/messaging/components/message-list-scroll-debug.test.ts",
  "app/features/messaging/services/dm-delivery-deterministic.integration.test.ts",
  "app/features/messaging/controllers/legacy/enhanced-dm-controller.ts",
  "app/features/messaging/controllers/legacy/enhanced-dm-controller.test.ts",
  "app/features/messaging/controllers/legacy/incoming-dm-event-handler.ts",
  "app/features/messaging/controllers/legacy/incoming-dm-event-handler.test.ts",
  "app/features/messaging/controllers/legacy/README.md",
  "app/features/messaging/controllers/outgoing-dm-orchestrator.ts",
  "app/features/messaging/controllers/outgoing-dm-orchestrator.test.ts",
  "app/features/messaging/controllers/outgoing-dm-publisher.ts",
  "app/features/messaging/controllers/outgoing-dm-publisher.test.ts",
  "app/features/messaging/controllers/outgoing-dm-send-preparer.ts",
  "app/features/messaging/controllers/outgoing-dm-send-preparer.test.ts",
  "app/features/messaging/controllers/relay-ok-message-handler.ts",
  "app/features/messaging/controllers/recipient-discovery-service.ts",
  "app/features/messaging/controllers/recipient-discovery-service.test.ts",
  "app/features/messaging/controllers/dm-queue-orchestrator.ts",
  "app/features/messaging/controllers/dm-queue-orchestrator.test.ts",
  "app/features/messaging/services/dm-conversation-materialization-owner.ts",
  "app/features/messaging/lib/__tests__/checkpoint-basic-sending.test.ts",
  "app/features/messaging/lib/__tests__/checkpoint-9-core-messaging-complete.test.ts",
  "app/features/messaging/lib/__tests__/enhanced-dm-controller.test.ts",
  "app/features/messaging/lib/__tests__/integration-complete-flows.test.ts",
  "app/features/messaging/lib/__tests__/integration-multi-relay-failover.test.ts",
  "app/features/messaging/lib/__tests__/integration-offline-online.test.ts",
  "app/features/messaging/lib/__tests__/message-receiving.test.ts",
  "app/features/messaging/lib/__tests__/message-sync.test.ts",
  "app/features/messaging/services/dm-local-delete-persistence.ts",
  "app/features/messaging/services/dm-local-delete-persistence.test.ts",
  "app/features/messaging/lib/retry-manager.ts",
  "app/features/messaging/lib/retry-manager.test.ts",
  "app/features/messaging/lib/offline-queue-manager.ts",
  "app/features/messaging/lib/offline-queue-manager.test.ts",
  "app/features/messaging/lib/performance-optimizer.ts",
  "app/features/messaging/lib/__tests__/performance-large-volumes.test.ts",
  "app/features/messaging/lib/message-ordering.test.ts",
  "app/features/search/hooks/use-mobile-discovery-compact-layout.snapshot.ts",
  "app/features/relays/services/relay-recovery-test-fixture.ts",
  "app/features/messaging/lib/message-flow-debugger.ts",
  "app/features/messaging/lib/message-logger.ts",
  "app/features/messaging/lib/fetch-link-preview.ts",
  "app/features/search/hooks/use-mobile-discovery-compact-layout.ts",
  "app/features/messaging/lib/dms/use-peer-trust.ts",
  "app/features/messaging/hooks/use-dm-controller.ts",
  "app/features/messaging/lib/dms/use-dm-controller.ts",
  "app/features/messaging/lib/relay-connection.ts",
  "app/features/messaging/lib/nostr-safety-limits.ts",
  "app/features/messaging/lib/dms/use-requests-inbox.ts",
  "app/features/messaging/services/dm-conversation-hydrate-sibling-diagnostics.ts",
  "app/features/messaging/hooks/use-conversation-messages.ts",
  "app/features/messaging/services/dm-conversation-hydrate-read-model.ts",
  "app/features/messaging/services/dm-conversation-hydrate-indexed-scan.ts",
  "app/features/messaging/services/dm-conversation-hydrate-indexed-map-rows.ts",
  "app/features/messaging/services/dm-conversation-projection-evidence-messages.ts",
  "app/features/messaging/services/dm-conversation-projection-live-merge.ts",
  "app/features/messaging/services/native-dm-thread-hydrate.ts",
  "app/features/messaging/services/dm-conversation-materialization-load-earlier.ts",
  "app/features/messaging/services/dm-conversation-materialization-realtime.ts",
  "app/features/relays/services/relay-recovery-policy.ts",
  "app/features/relays/hooks/enhanced-relay-pool.ts",
  "app/features/groups/hooks/use-sealed-community.ts",
  "app/features/groups/providers/group-provider.tsx",
  "app/features/messaging/services/chat-state-store.ts",
  "app/legacy/relay-recovery-policy-legacy.ts",
  "app/legacy/dm-conversation-projection-evidence-messages-legacy.ts",
  "app/legacy/dm-conversation-projection-live-merge-legacy.ts",
  "app/legacy/dm-conversation-materialization-load-earlier-legacy.ts",
  "app/legacy/dm-conversation-materialization-realtime-legacy.ts",
  "app/legacy/native-dm-thread-hydrate-legacy.ts",
  "app/legacy/dm-conversation-hydrate-indexed-scan-legacy.ts",
  "app/legacy/dm-conversation-hydrate-indexed-map-rows-legacy.ts",
  "app/legacy/dm-conversation-hydrate-read-model-legacy.ts",
  "app/legacy/dm-read-authority-contract-legacy.ts",
  "app/legacy/dm-conversation-hydrate-pipeline-legacy.ts",
  "app/legacy/native-dm-conversation-hydrate-owner-legacy.ts",
  "app/legacy/use-conversation-messages-legacy.ts",
  "app/legacy/use-sealed-community-legacy.ts",
  "app/legacy/group-provider-legacy.tsx",
  "app/legacy/enhanced-relay-pool-legacy.ts",
  "app/legacy/chat-state-store-legacy.ts",
] as const;

export const OBSCUR_ENGINE_PACKAGE_ROOTS = [
  "packages/obscur-engine-contracts",
  "packages/obscur-engine-host",
  "packages/obscur-dm-engine",
  "packages/obscur-transport-engine",
  "packages/obscur-workspace-engine",
  "packages/obscur-auth-engine",
] as const;
